# PyTest workflow

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]  # tensorflow not supported with 3.12
        os: [ ubuntu-latest, windows-latest ]
        include:
          - python-version: "3.11"
            os: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          # Install local package with tests dependencies extras
          python -m pip install --upgrade pip
          # TODO remove this when v0.5.0 is out
          pip install git+https://github.com/Yikai-Liao/symusic
          pip install -e ".[tests]"

      - name: Test with pytest
        run: pytest --cov=./ --cov-report=xml -n logical --durations=0 -v tests
        env:
          HF_TOKEN_HUB_TESTS: ${{ secrets.HF_TOKEN_HUB_TESTS }}

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install build
      - name: Build package
        run: python -m build
